name: boost_notes
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.6.0
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  ###
  flutter_bloc: ^9.1.1
  flutter_svg: ^2.2.1
  go_router: ^16.3.0
  shared_preferences: ^2.5.3
  intl: ^0.20.2

  # others
  connectivity_plus: ^7.0.0
  smooth_page_indicator: ^1.2.1
  flutter_dotenv: ^6.0.0
  url_launcher: ^6.3.2
  lottie: ^3.3.2
  gradient_borders: ^1.0.2
  flutter_markdown: ^0.7.7+1
  permission_handler: ^12.0.1
  pull_to_refresh: ^2.0.0

  # picker
  # file_picker: ^6.1.1

  # auth
  google_sign_in: ^7.2.0
  sign_in_with_apple: ^7.0.1
  device_info_plus: ^12.3.0

  # voice
  record: ^6.1.2
  just_waveform: ^0.0.7

  # network
  dio: ^5.9.0

  # db
  sqflite: ^2.4.2
  path: ^1.9.1

  ###
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  # change_app_package_name: ^1.5.0 # dart run change_app_package_name:main com.pump.voice.app
flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/
    - assets/fonts/
    - assets/icons/
    - assets/onboard/
  fonts:
    - family: w500
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf
    - family: w600
      fonts:
        - asset: assets/fonts/Poppins-SemiBold.ttf
    - family: w700
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf